### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by trancexe** [simda-id/simcan#10]
.env masih memungkinkan untuk didownload via url www.contohweb.com/protected/.env

**Comment by sisawaktu** [comment]
server sudah membaca .htaccess nya ?

**Comment by trancexe** [comment]
Saya test lagi terblock dg baik. Mungkin gara2 saya mainan htaccess. Di simcan udah ada proteksi biar ga ke index. Kyanya ketimpa ama htaccess orinya laravel
