### ISSUE TITLE
Eror Load Forum PD

### ISSUE THREAD

**Issue by mustangin** [simda-id/simcan#12]
Load Forum OPD Eror
![image](https://user-images.githubusercontent.com/12058841/51013097-39773400-1593-11e9-94d9-7640831b31bb.png)

Dilihat Muncul Seperti ini
![image](https://user-images.githubusercontent.com/12058841/51013085-2a908180-1593-11e9-969e-df1839fb780b.png)

**Comment by pilmanux** [comment]
Ganti ke rilis yang lebih baru..

**Comment by mustangin** [comment]
sudah bisa, tapi ada eror saat upddate ke versi terbaru muncul seperti ini
![image](https://user-images.githubusercontent.com/12058841/66536502-5c953b00-eb47-11e9-90ac-080c9e7829d4.png)
