### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by r1d0** [simda-id/simcan#14]
Bagaimana cara update DB ke versi ini ? apa ada script khusus hanya update ?

**Comment by kangsis** [comment]
mohon info cara instalasi simda perencanaan di linux ubuntu server 16, file apa saja yang diubah permissionnya dll, terima kasih

**Comment by lusianto1978** [comment]
Banyak bro, file .env debugnya di di berikan tanda true

**Comment by pilmanux** [comment]
1. update db.. lakukan sinkronisasi struktur db dengan menggunakan  Navicat
2. Pengalaman tidak ada yang harus diubah permissionnya jika menggunakan cPanel atau sejenis yang gratisan seperti Virtualmin yang dijalankan pada Ubuntu Server

**Comment by lusianto1978** [comment]
Siap mas aku aku update

Pada tanggal Jum, 4 Des 2020 15:24, mramadhan77 <notifications@github.com>
menulis:
