### ISSUE TITLE
No such file or directory in

### ISSUE THREAD

**Issue by xcdhitam** [simda-id/simcan#15]
![error file](https://user-images.githubusercontent.com/17157616/63226983-b21a2f00-c20b-11e9-9d49-bfeff1bc2e74.png)

file menu tidak ada atau saya yang salah confignya

**Comment by mramadhan77** [comment]
menu.php merupakan bagian dari config yang dapat diminta ke perwakilan BPKP

**Comment by xcdhitam** [comment]
oke sip
