### ISSUE TITLE
Beberapa Controller Tidak Ditemukan Ketika Run di Server Linux-based

### ISSUE THREAD

**Issue by putuariepra** [simda-id/simcan#16]
OS: Ubuntu 16.04

Saya menemui kendala ketika production di Server Linux-based, salah satunya yaitu:
`[2019-09-09 09:45:04] local.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\TrxCetakTahunanController does not exist' in /var/www/e-planningintegrated/protected/vendor/laravel/framework/src/Illuminate/Container/Container.php:729`

Kemungkinan ini terjadi karena case-sensitive dimana pada simcan terdapat 2 folder Http yaitu (http dan Http). 
![Screenshot from 2019-09-09 14 08 10](https://user-images.githubusercontent.com/12608555/64506756-44918800-d30b-11e9-91a5-9cdc655c92ae.png)

Saya sudah coba mengduplikasi semua file yang ada di http ke Http dan hasilnya beberapa fitur yang terkait dengan controller tsb dapat digunakan kembali. 

Untuk release berikutnya apakah tidak bisa file pada folder http dijadikan 1 pada Http? _(seperti laravel pada umumnya)_
Mohon petunjuknya. Terima kasih

**Comment by pilmanux** [comment]
Pakai saja Rilis yang terbaru..

**Comment by putuariepra** [comment]
Kami sdh di berikan release yg terbaru oleh perwakilan BPKP di daerah kami, dan sudah fix. terima kasih
