### ISSUE TITLE
error saat menggunakan versi sept: 20190908

### ISSUE THREAD

**Issue by ghostnet06** [simda-id/simcan#17]
![image](https://user-images.githubusercontent.com/55083728/64518893-4401ed00-d31d-11e9-8a10-4c6003900794.png)

minta tolong dibantu solusinya. Makasih

**Comment by lusianto1978** [comment]
Di install composer nya

**Comment by atamela** [comment]
![image](https://user-images.githubusercontent.com/56379039/66891611-d7f95f80-f013-11e9-8173-e09a9417822c.png)

Sudah Instal Composer, masih error.
Apakah ada settingan lagi ?

baru mau coba simulasi, dari Kabupaten Aceh Tamiang.

![image](https://user-images.githubusercontent.com/56379039/66891750-1f7feb80-f014-11e9-8377-367c493b9eb4.png)

**Comment by nantobae** [comment]
install composer gimana caranya pak Lusi?... masih bingung pak, maklum newbie disuruh belajar simcan

**Comment by lusianto1978** [comment]
Kalau phpnya 7.3 pakai yang app72 di github

**Comment by nantobae** [comment]
PHP Version 5.6.36 pak..

**Comment by lusianto1978** [comment]
Kalau 5.6 sampai 7.0 kalau yang baru ada yang bisa 7.1 samapai 7.3
