### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by r1d0** [simda-id/simcan#18]
HTTP ERROR 500 ???ver 0904 apa pengaruh config harus minta yang baru juga pak ?

**Comment by pilmanux** [comment]
Ada file yang kurang biasanya..

**Comment by pilmanux** [comment]
install composernya

**Comment by adjarriawan** [comment]
Warning: App\MenuForm::getApp(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

**Comment by adjarriawan** [comment]
rename file pada folder config **menu_on_simulasi.php** menjadi **menu.php**
