### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by madhanp** [simda-id/simcan#22]
![Screenshot 2019-11-05 at 15 13 45](https://user-images.githubusercontent.com/3401260/68186365-f0d7ae00-ffde-11e9-96b7-fc0700a954a4.png)
mohon bantuannya sy menginstall simcan versi 20191020 namun eror seperti gamabr berikut?

**Comment by itankjs** [comment]
belum ada solusinya?, pada slow respon

**Comment by devies-dmv** [comment]
maksudnya gimana, error waktu akses or???

**Comment by madhanp** [comment]
blm ada solusinya pak, eror setelah update versi 70, sy bisa d bantu pak
untuk update versi salaview nnti sy kasi cpanel hosting saya?

Pada tanggal Jum, 22 Nov 2019 pukul 22.39 devies-dmv <
notifications@github.com> menulis:

**Comment by wawan05** [comment]
Siapa tau saya bisa bantu pak dari Gowa, Sul-Sel.. wa ke 085398814888

**Comment by farisdenanda** [comment]
> ![Screenshot 2019-11-05 at 15 13 45](https://user-images.githubusercontent.com/3401260/68186365-f0d7ae00-ffde-11e9-96b7-fc0700a954a4.png)
> mohon bantuannya sy menginstall simcan versi 20191020 namun eror seperti gamabr berikut?

Database nya tidak terbaca ini mas
