### ISSUE TITLE
Problem Detec

### ISSUE THREAD

**Issue by farisdenanda** [simda-id/simcan#24]
![WhatsApp Image 2020-01-10 at 13 51 14](https://user-images.githubusercontent.com/30820160/72129296-b0b2f400-33b0-11ea-9f38-6fab9797ddd5.jpeg)
Dalam database 5 tahunan, Pendapatan dan Belanja Tidak Langsung Langsung sudah di inputkan data ketika Data sudah terkirim di aplikasi Simda Perencanaan Tahunan Data tidak tampil.
Lebih detail Masalah yang ditemukan, dilampirkan sebagai file
[text.docx](https://github.com/simda-id/simcan/files/4044254/text.docx)

Mohon bantuan petunjuknya.

**Comment by harkita** [comment]
Jenis_belanja pada trx_rkpd_ranwal = 0. 
Harusnya pendapatan  1, btl 2.. cmiiw

**Comment by farisdenanda** [comment]
1. Proses Load Dalam RPJMD dan Pendapatan Tidak langsung Indikator nya 0
padahal Dalam simda Perencanaan Desktop sudah di input semua. apakah ini
yang membuat Jenis_belanja pada trx_rkpd_ranwal = 0.
2. lampiran Text
Mohon Bantuannya, Terimakasih

Pada tanggal Jum, 10 Jan 2020 pukul 14.40 harkita <notifications@github.com>
menulis:
