### ISSUE TITLE
eror cetak ssh di hosting 

### ISSUE THREAD

**Issue by madhanp** [simda-id/simcan#26]
![Screen Shot 2020-02-26 at 14 45 15](https://user-images.githubusercontent.com/3401260/75320201-2ca5c480-58a9-11ea-936d-7cb91e0bd799.png)

**Comment by mrizkir** [comment]
Kalau ini disebabkan mungkin pdf previewnya gak tersedia

**Comment by madhanp** [comment]
p

> Kalau ini disebabkan mungkin pdf previewnya gak tersedia

ada pak TCPDFnya, klo d local jalan normal pdfnya, tapi d hosting jadi begitu
