### ISSUE TITLE
Blank Page in Ubuntu Server

### ISSUE THREAD

**Issue by faridzy** [simda-id/simcan#4]
Saya install di ubuntu server terjadi masalah ketika diakses terjadi blank page

**Comment by simda-indonesia** [comment]
- versi php 5.6?
- ioncube sudah dipasang?
- versi mysql 5.5?
- config sudah dipasang?
- .env sudah sesuai?
- apache versi 2?
- server sudah terkoneksi ke internet?

**Comment by faridzy** [comment]
Sudah mas apa perlu settingan selanjutnya ketika display error saya on kan,
muncul laravel error cannot load container

Pada tanggal 24 Des 2017 4.46 AM, "simda-indonesia" <
notifications@github.com> menulis:

**Comment by simda-indonesia** [comment]
silakan dicoba ambil kembali file .env -nya, yang sudah dihilangkan comment-nya.
https://github.com/simda-id/simcan/blob/master/protected/.env
