### ISSUE TITLE
dbsimcan kabupaten dompu ntb

### ISSUE THREAD

**Issue by putraagungeko** [simda-id/simcan#7]
kami kesulitan dalam pengaplikasian simcan tahunan, permasalahan sebagai berikut
1. nama kadis tidak terisi langsung pada penambahan dokumen ranwal dan dokumen rancangan renja
2. proses load musrenbang desa terdapat pesan gagal undefined, lokasi musrenbang desa dan rt tidak ikut terload
3. akibat dari nomor 2 seluruh proses selanjutnya dipastikan eror

**Comment by simda-indonesia** [comment]
mohon dengan sangat untuk memperhatikan kembali tatacara input data di aplikasi.
hubungi perwakilan BPKP untuk lebih jelasnya.

1. Untuk masuk ke Rancangan Renja harus menyelesaikan Dokumen Ranwal RKPD.
2. Untuk masuk ke proses Musrenbang harus ditetapkan aktivitas yang ditawarkan di musrenbang; ini dilakukan dalam proses penyusunan renja.
3. Untuk mendapatkan data aktivitas yang akan ditawarkan di musrenbang harus difinalkan data ASB terlebih dahulu.
