### ISSUE TITLE
hehe

### ISSUE THREAD

**Issue by akhwan90** [simda-id/simcan#9]
![screenshot_22](https://user-images.githubusercontent.com/6227763/43240690-e945882a-90c1-11e8-871e-f66d9b1d4ae5.png)
mau ngembangin gimana, kalo soskod di enkrip :D :D

**Comment by mustangin** [comment]
iya, source code masih di enkripsi. cuma kasih saran perbaikan dan mungkin tim simda yang mengembangkan.
